/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.akuavida.negocio.ejemplo2;

import edu.co.sena.akuavida.negocio.example.*;
import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.akuavida.integracion.dao.PromocionesDao;
import edu.co.sena.akuavida.integracion.dto.Promociones;
import edu.co.sena.akuavida.integracion.exceptions.PromocionesDaoException;
import edu.co.sena.akuavida.integracion.factory.PromocionesDaoFactory;

public class PromocionesDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByProducto("");
		// findWhereIdPromocionEquals("");
		// findWhereDescuentosEquals(0);
		// findWhereNombreEquals("");
		// findWherePrecioEquals(0);
		// findWhereProductoIdProductoEquals("");
            Promociones prom1 = new Promociones();
            prom1.setIdPromocion("01");
            prom1.setDescuentos(16);
            prom1.setNombre("Pague 1 lleve 3");
            prom1.setPrecio(160000);
            prom1.setProductoIdProducto("01");
            
            PromocionesDao promDao = getPromocionesDao();
            promDao.insert(prom1);
            System.out.println("Se inserto la Promocion");
            prom1.setNombre("Pague las tres por loka");
            prom1.setPrecio(150000);
            promDao.update(prom1.createPk(), prom1);
            System.out.println("Se actualizo los datos");
            findAll();
            
            
            
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			PromocionesDao _dao = getPromocionesDao();
			Promociones _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByProducto'
	 * 
	 * @param productoIdProducto
	 */
	public static void findByProducto(String productoIdProducto)
	{
		try {
			PromocionesDao _dao = getPromocionesDao();
			Promociones _result[] = _dao.findByProducto(productoIdProducto);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdPromocionEquals'
	 * 
	 * @param idPromocion
	 */
	public static void findWhereIdPromocionEquals(String idPromocion)
	{
		try {
			PromocionesDao _dao = getPromocionesDao();
			Promociones _result[] = _dao.findWhereIdPromocionEquals(idPromocion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDescuentosEquals'
	 * 
	 * @param descuentos
	 */
	public static void findWhereDescuentosEquals(float descuentos)
	{
		try {
			PromocionesDao _dao = getPromocionesDao();
			Promociones _result[] = _dao.findWhereDescuentosEquals(descuentos);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNombreEquals'
	 * 
	 * @param nombre
	 */
	public static void findWhereNombreEquals(String nombre)
	{
		try {
			PromocionesDao _dao = getPromocionesDao();
			Promociones _result[] = _dao.findWhereNombreEquals(nombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePrecioEquals'
	 * 
	 * @param precio
	 */
	public static void findWherePrecioEquals(float precio)
	{
		try {
			PromocionesDao _dao = getPromocionesDao();
			Promociones _result[] = _dao.findWherePrecioEquals(precio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProductoIdProductoEquals'
	 * 
	 * @param productoIdProducto
	 */
	public static void findWhereProductoIdProductoEquals(String productoIdProducto)
	{
		try {
			PromocionesDao _dao = getPromocionesDao();
			Promociones _result[] = _dao.findWhereProductoIdProductoEquals(productoIdProducto);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getPromocionesDao'
	 * 
	 * @return PromocionesDao
	 */
	public static PromocionesDao getPromocionesDao()
	{
		return PromocionesDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Promociones dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdPromocion() );
		buf.append( ", " );
		buf.append( dto.getDescuentos() );
		buf.append( ", " );
		buf.append( dto.getNombre() );
		buf.append( ", " );
		buf.append( dto.getPrecio() );
		buf.append( ", " );
		buf.append( dto.getProductoIdProducto() );
		System.out.println( buf.toString() );
	}

}
